name: 🧑‍💻 Feature Request
description: Suggest an idea for this project
title: "feat: "
labels: ["🌟 enhancement"]
body:
  - type: textarea
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is.
    validations:
      required: true
